version: "3.7"

services:

  client:
    build: ./client
    restart: on-failure
    ports:
      - 80:3000
    networks:
      - client
    environment:
      SERVER_CONTAINER: server
    volumes:
      - type: volume
        source: client_modules
        target: /client/node_modules
        volume:
          nocopy: true
    labels:
      com.docker.lb.hosts: "localhost"
      com.docker.lb.sticky_session_cookie: "AUTH_TOKEN"
      com.docker.lb.port: 3000

    depends_on:
      - server
  
  server:
    build: ./server
    restart: on-failure
    ports:
      - 9000:9000
    networks:
      - server
    volumes:
      - type: volume
        source: server
        target: /server
        volume:
          nocopy: true
      - type: volume
        source: server_modules
        target: /server/node_modules
        volume:
          nocopy: true
    env_file: ./server/node_env.env
    depends_on:
      - db
  
  db:
    image: mongo
    restart: on-failure
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: cms
    networks: 
      - server
    volumes:
      - type: volume
        source: db
        target: /data/db
        volume:
          nocopy: true
  
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: password
      ME_CONFIG_MONGODB_SERVER: db
    networks: 
      - server
  
volumes:
  client_modules:
  server:
  server_modules:
  db:

networks:
  client:
  server:
    